language: cpp

matrix:
  include:
     - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

before_install:
    - eval "${MATRIX_EVAL}"


before_install:
  - eval "${MATRIX_EVAL}"

dist: xenial

script:
  - git ls-files src/ | xargs clang-format -i && git diff --exit-code
  - make

compiler:
  -g++